apiVersion: batch/v1
kind: Job
metadata:
  name: free5gc-prep-job
  namespace: default
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - name: ansible-job
        image: 192.168.230.50:51002/free5gc-prep:1.0.0
        command: ["/bin/bash", "-c", "echo 'Job is running'; sleep 10"]
      restartPolicy: Never
