---
- name: Setup Free5GC Environment
  hosts: all
  vars:
    ansible_become_pass: 1
  become: true
  tasks:
    - name: Create /root/kubedata directory
      ansible.builtin.file:
        path: /root/kubedata
        state: directory
        mode: '0755'

    - name: Create /root/5gc directory
      ansible.builtin.file:
        path: /root/5gc
        state: directory
        mode: '0755'

    - name: Install Multus CNI using kubectl
      ansible.builtin.command:
        cmd: kubectl apply -f https://raw.githubusercontent.com/k8snetworkplumbingwg/multus-cni/master/deployments/multus-daemonset.yml
      register: result
      changed_when: "'configured' in result.stdout"

